import { ReactNode } from 'react'
import Head from 'next/head'
import { GlobalTheme } from '@carbon/react'
import '../../styles/Layout.module.scss'

interface Props {
  children: ReactNode
}
export default function Layout({ children }: Props) {
  return (
    <GlobalTheme theme="g100">
      <Head>
        <title>livecode</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>{children}</main>
    </GlobalTheme>
  )
}
